### ISSUE TITLE
Problems highlighted by test cases

### ISSUE THREAD

**Issue by andym2009** [jalder/UPnP#1]
Hi,

I am using PHP 5.5 on a Mac and have installed the prerequisites.

When I try to run the tests line 27 in core.php throws an error. (Unable to set socket option [22]: Invalid argument).

I had to change from

```
    socket_set_option($socket, 1, 6, true);
```

to

```
    socket_set_option($socket, SOL_SOCKET, SO_BROADCAST, true);
```

I also found that it depended on having curl installed (which is not the case by default in the mac at least).

Tests are now working :-)

Many thanks

A.

```
    socket_set_option($socket, SOL_SOCKET, SO_BROADCAST, true);
```

**Comment by jalder** [comment]
Thanks! I'll get this adjusted as soon as possible. Not sure why I wasn't using the PHP constants all along to be honest.

**Comment by andym2009** [comment]
No problem, I think a lot of people used those values at the start, I think they must've changed recently.

Can I ask a favour?

I have been developing software for 30 years, so I'm not totally clueless but my PHP knowledge is dated (no time to update it right now) and after years using Microsoft stuff last year I made the leap over to Apple. I opted for phpstorm as an IDE and have figured out most things but so far the challenge of protobuf has foxed me.

I used macports to install it, but of course it only supports, c++, Java and Python not PHP.

I found a variety of libraries to support use with PHP, including the one you used on GitHub but up until now I have not figured out how to use them in conjunction with your library.

As far as I can tell your code is assuming the protobuf message class will be autoloaded, but right now I have not found a way to ensure that happens.

Is there any chance you could drop me an idiot's guide on how to use the protobuf-PHP library with yours?

I don't think the one you used has a composer installation, though some others do.

I am away at the moment, back on Friday, but any help you have time to give me would be greatly appreciated.

Many thanks.

Andy

**Comment by bryceadams** [comment]
@jalder I made a PR to fix this issue.
